name: wine-model-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.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 }}
        
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
          CML_GITHUB_TOKEN: ${{ secrets.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 }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

          echo "MODEL METRICS MESURE" 
          cat metrics.txt 

          cml-publish residuals.png --md >> report.md
